# Generated by Django 4.2.7 on 2025-08-14 02:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Medication name')),
                ('dosage', models.CharField(help_text='e.g., 500mg, 2 tablets', max_length=50, verbose_name='Dosage')),
                ('frequency', models.CharField(choices=[('once_daily', 'Once daily'), ('twice_daily', 'Twice daily'), ('three_times_daily', 'Three times daily'), ('four_times_daily', 'Four times daily'), ('every_8_hours', 'Every 8 hours'), ('every_12_hours', 'Every 12 hours'), ('as_needed', 'As needed'), ('custom', 'Custom')], default='once_daily', max_length=20, verbose_name='Frequency')),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, help_text='Scheduled times for taking medication', size=8)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions', verbose_name='Notes')),
                ('color', models.CharField(help_text='Hex color code for UI display', max_length=7, verbose_name='Color')),
                ('medication_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20, verbose_name='Type')),
                ('condition', models.CharField(blank=True, help_text='Condition this medication treats', max_length=100, verbose_name='Medical condition')),
                ('prescriber', models.CharField(blank=True, max_length=100, verbose_name='Prescribing doctor')),
                ('prescription_date', models.DateField(blank=True, null=True, verbose_name='Prescription date')),
                ('total_pills', models.PositiveIntegerField(blank=True, help_text='Total quantity available', null=True, verbose_name='Total pills/doses')),
                ('remaining_pills', models.PositiveIntegerField(blank=True, help_text='Current remaining quantity', null=True, verbose_name='Remaining pills/doses')),
                ('low_stock_alert', models.PositiveIntegerField(default=5, help_text='Alert when remaining pills/doses reach this number', verbose_name='Low stock alert threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medications',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('deleted', 'Deleted')], max_length=20, verbose_name='Action')),
                ('changes', models.JSONField(default=dict, help_text='JSON object with field changes', verbose_name='Changes')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medications.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication History',
                'verbose_name_plural': 'Medication History',
                'db_table': 'medication_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['user', 'is_active'], name='medications_user_id_2d9b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['user', 'name'], name='medications_user_id_0fa514_idx'),
        ),
    ]
